import { Schema, Table, column } from "@powersync/web";

export const AppSchema = new Schema({
  products: new Table({
    tenant_id: column.text,
    category_id: column.text,
    name: column.text,
    description: column.text,
    price: column.real,
    cost_price: column.real,
    sku: column.text,
    image_url: column.text,
    is_active: column.integer,
    tax_rate: column.real,
    product_type: column.text,
    tags: column.text,
    display_order: column.integer,
    status: column.text,
    is_upsell: column.integer,
    is_manufactured_on_site: column.integer,
    available_order_type_codes: column.text,
    visible_tenant_ids: column.text,
    delivery_price: column.real,
    price_glovo: column.real,
    price_kooul: column.real,
    updated_at: column.text,
  }),

  categories: new Table({
    tenant_id: column.text,
    name: column.text,
    description: column.text,
    color: column.text,
    image_url: column.text,
    display_order: column.integer,
    parent_category_id: column.text,
    is_active: column.integer,
  }),

  customization_phases: new Table({
    tenant_id: column.text,
    name: column.text,
    description: column.text,
    selection_type: column.text,
    min_selections: column.integer,
    max_selections: column.integer,
    is_required: column.integer,
    is_active: column.integer,
    display_title: column.text,
    enabled_terminal: column.integer,
    enabled_pos: column.integer,
    use_large_buttons: column.integer,
  }),

  customization_options: new Table({
    tenant_id: column.text,
    phase_id: column.text,
    name: column.text,
    price_adjustment: column.real,
    image_url: column.text,
    is_available: column.integer,
    display_order: column.integer,
    product_id: column.text,
    sub_phase_ids: column.text,
    group_id: column.text,
    disable_phase_ids: column.text,
    disable_option_ids: column.text,
    is_default: column.integer,
    available_order_type_codes: column.text,
    delivery_price: column.real,
    price_glovo: column.real,
    price_kooul: column.real,
  }),

  customization_option_groups: new Table({
    tenant_id: column.text,
    phase_id: column.text,
    name: column.text,
    display_order: column.integer,
    is_active: column.integer,
    min_selections: column.integer,
    max_selections: column.integer,
  }),

  product_customization_phases: new Table({
    tenant_id: column.text,
    product_id: column.text,
    phase_id: column.text,
    display_order: column.integer,
  }),

  order_types: new Table({
    tenant_id: column.text,
    code: column.text,
    name: column.text,
    icon: column.text,
    display_order: column.integer,
    enabled_pos: column.integer,
    enabled_terminal: column.integer,
    is_active: column.integer,
    color: column.text,
    is_offert: column.integer,
  }),

  payment_methods: new Table({
    tenant_id: column.text,
    code: column.text,
    name: column.text,
    icon: column.text,
    enabled_pos: column.integer,
    enabled_terminal: column.integer,
    display_order: column.integer,
    is_active: column.integer,
    available_order_type_codes: column.text,
    enabled_click_collect: column.integer,
  }),

  tenant_settings: new Table({
    tenant_id: column.text,
    logo_url: column.text,
    primary_color: column.text,
    terminal_primary_color: column.text,
    terminal_background_color: column.text,
    terminal_welcome_image_url: column.text,
    terminal_welcome_video_url: column.text,
    pos_primary_color: column.text,
    pos_background_color: column.text,
    kitchen_primary_color: column.text,
    kitchen_background_color: column.text,
    cc_primary_color: column.text,
    cc_secondary_color: column.text,
    cc_background_color: column.text,
    cc_lead_time_minutes: column.text,
    default_currency: column.text,
    receipt_template: column.text,
    kitchen_ticket_template: column.text,
    card_receipt_template: column.text,
    offert_enabled: column.integer,
    loyalty_enabled: column.integer,
    online_payment_enabled: column.integer,
    timezone: column.text,
    business_day_start_hour: column.integer,
    updated_at: column.text,
  }),

  establishments: new Table({
    tenant_id: column.text,
    name: column.text,
    address: column.text,
    phone: column.text,
    email: column.text,
    is_active: column.integer,
    pos_enabled: column.integer,
    terminal_enabled: column.integer,
    kitchen_enabled: column.integer,
    display_enabled: column.integer,
  }),

  tenants: new Table({
    name: column.text,
    slug: column.text,
    parent_tenant_id: column.text,
    plan: column.text,
    is_active: column.integer,
  }),

  pos_transactions: new Table({
    tenant_id: column.text,
    session_id: column.text,
    user_id: column.text,
    transaction_number: column.text,
    subtotal: column.real,
    tax_amount: column.real,
    discount_amount: column.real,
    total_amount: column.real,
    payment_method: column.text,
    amount_received: column.real,
    change_given: column.real,
    status: column.text,
    notes: column.text,
    source: column.text,
    order_type: column.text,
    customer_id: column.text,
    is_offert: column.integer,
    customer_name: column.text,
    customer_phone: column.text,
    table_id: column.text,
    paid_at: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),

  pos_transaction_items: new Table({
    transaction_id: column.text,
    product_id: column.text,
    quantity: column.integer,
    unit_price: column.real,
    discount_amount: column.real,
    total_price: column.real,
    selected_options: column.text,
    notes: column.text,
    order_type_code: column.text,
  }),

  pos_sessions: new Table({
    tenant_id: column.text,
    user_id: column.text,
    session_number: column.text,
    start_time: column.text,
    end_time: column.text,
    opening_balance: column.real,
    closing_balance: column.real,
    total_sales: column.real,
    total_transactions: column.integer,
    status: column.text,
  }),

  customers: new Table({
    tenant_id: column.text,
    first_name: column.text,
    last_name: column.text,
    phone: column.text,
    email: column.text,
    birth_date: column.text,
    created_at: column.text,
  }),

  loyalty_accounts: new Table({
    tenant_id: column.text,
    customer_id: column.text,
    points_balance: column.integer,
    total_earned: column.integer,
    total_redeemed: column.integer,
    last_activity_at: column.text,
  }),

  loyalty_rewards: new Table({
    tenant_id: column.text,
    program_id: column.text,
    name: column.text,
    points_cost: column.integer,
    reward_type: column.text,
    reward_value: column.real,
    product_id: column.text,
    image_url: column.text,
    display_order: column.integer,
    is_active: column.integer,
  }),

  kitchen_orders: new Table({
    tenant_id: column.text,
    transaction_id: column.text,
    order_number: column.text,
    items: column.text,
    status: column.text,
    priority: column.integer,
    notes: column.text,
    started_at: column.text,
    completed_at: column.text,
    customer_name: column.text,
    customer_phone: column.text,
    order_source: column.text,
    order_type: column.text,
    payment_method: column.text,
    pickup_time: column.text,
    order_token: column.text,
    online_payment_status: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),

  restaurant_tables: new Table({
    tenant_id: column.text,
    zone_id: column.text,
    name: column.text,
    capacity: column.integer,
    status: column.text,
    current_order_id: column.text,
    display_order: column.integer,
    is_active: column.integer,
    pos_x: column.real,
    pos_y: column.real,
    shape: column.text,
  }),

  restaurant_zones: new Table({
    tenant_id: column.text,
    name: column.text,
    floor: column.text,
    display_order: column.integer,
    is_active: column.integer,
  }),

  profiles: new Table({
    tenant_id: column.text,
    email: column.text,
    first_name: column.text,
    last_name: column.text,
    role: column.text,
    establishment_id: column.text,
    two_factor_enabled: column.integer,
  }),
});

export type AppDatabase = typeof AppSchema;
